/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    NeighborContentDetail: typeof import('./components/NeighborContentDetail.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialFeedContent: typeof import('./components/SocialFeedContent.vue')['default']
    UserStatusCard: typeof import('./components/UserStatusCard.vue')['default']
  }
}
